# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc5a1a94c077cedad0924ea4745f8786d5e7a5032b3965b519f98262f08a95c52a3de4dbd199a108d66ef7f26ffd8c4195e11c7d47588c79a2a7a77a60117eb

test:
  secret_key_base: 107019163a63ff299065769fb7746561cdd06cf1d88b8c823cc2fe191f9eeb92ba10ef0a8cc34fce9a03a23b2dceae9841788ba61759b80b0083b3203d9813e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  host: YOUR PRODUCTION HOST URL/IP HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>